name: Build and Push to Nexus

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    strategy:
      matrix:
        service:
          - frontend
          - backend
          - api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Local Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.NEXUS_URL }}/${{ matrix.service }}:latest
            ${{ secrets.NEXUS_URL }}/${{ matrix.service }}:${{ github.sha }}