name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-sonarqube:
    name: Frontend SonarQube Scan
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: SonarQube Scan - Frontend
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: frontend

  backend-sonarqube:
    name: Backend SonarQube Scan
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: SonarQube Scan - Backend
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: backend

  api-sonarqube:
    name: API SonarQube Scan
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: SonarQube Scan - API
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: api
